### ISSUE TITLE
WebRTC connection issues

### ISSUE THREAD

**Issue by louiscenter** [louiscenter/hypervision-browser#1]
_NOTE: To test the app yourself, the latest version is hosted here for your convenience: [https://hypervisionbrowser.surge.sh](https://hypervisionbrowser.surge.sh)_

When trying to broadcast and then watch the same live stream, either from a different window, or another computer, a series of connection issues arise.

- 25% of the time, the first chunk of video will appear, but then pause immediately after that.
- 25% of the time, the video will continue as per normal for anywhere between 10-25 seconds, and then eventually stop.
- 50% of the time, the stream won't connect/play at all.

(There is usually far more success connecting to the peer if you're connecting from the same computer/browser, rather than from a remote connection)

In the devtools console, the most common error that appears is a `premature close` error from `pump`. This happens on both the broadcast end, and the viewers end.

In Chrome's `webrtc-internals` page, the most common error that appears is the following:
`setRemoteDescriptionOnFailure - Failed to set remote offer sdp: Called in wrong state: STATE_SENTOFFER`.

The broadcaster will continue to append new video chunks to the `hypercore` feed, but after connection issues arise, the video stream won't start working again. Clients are connecting to `signalhub` a-ok, so the assumption here is that there are `webrtc` connection issues between the two peers.

cc @mafintosh @feross

**Comment by louiscenter** [comment]
Another error that has started appearing on the `webrtc-internals`page:

```
addIceCandidateFailed
sdpMid: data, sdpMLineIndex: 0, candidate: candidate:345893049 1 tcp 1518280447 192.168.0.2 9 typ host tcptype active generation 1 ufrag HWeN network-id 1 network-cost
```

**Comment by feross** [comment]
Just speaking from a `simple-peer` perspective, the error message "Called in wrong state" usually implies that `simple-peer` is being used incorrectly. See: https://github.com/feross/simple-peer/search?q=Called+in+wrong+state&type=Issues&utf8=%E2%9C%93
